apps/processor/models.py
from datetime import datetime

from apps.app import db

class Answer(db.Model):
    __tablename__ = "answers"
    id = db.Column(db.Integer, primary_key=True)
    uuid = db.Column(db.String)
    image_path = db.Column(db.String)
    audio_path = db.Column(db.String)
    processed = db.Column(db.Boolean)
    threshold = db.Column(db.Integer)
    window_length = db.Column(db.Integer)
    pitch_shifted = db.Column(db.Boolean)
    pitch_shift = db.Column(db.Integer)
    created_at = db.Column(db.DateTime, default=datetime.now)

apps/processor/__init__.py
import apps.processor.models

apps/processor/views.py
import soundfile as sf
from datetime import datetime
from pathlib import Path
from apps.app import db
from apps.processor.models import Answer

# 音声を加工する関数を読み込む
import apps.processor.process as process

# Flask関連
from flask import Blueprint, render_template, request, current_app, send_from_directory, session, url_for, redirect

processor = Blueprint("processor", __name__, template_folder="templates", static_folder="static")

@processor.route("/<number>", methods=["GET", "POST"])
def index(number):
    number = int(number)
    if request.method == "GET":
        return render_template("processor/index.html", result={}, imagefile=session["target_images"][number], number=number)
    if request.method == "POST":
        # formの入力を辞書型で取得
        result = request.form.to_dict()
        infile = current_app.config["UPLOAD_FOLDER"] + "/" + session["original_audio"][number]
        filename = "processed_audio/" + session["uuid"] + datetime.now().strftime("%Y%m%d%H%M%S") + ".wav"
        filepath = Path(
            current_app.config["UPLOAD_FOLDER"], filename
        )
        if result["button"] == "再生":
            input_audio, fs = sf.read(infile)
            if "pitch_toggle" in result:
                shift = int(result["pitch_shift"])
                input_audio, fs = process.pitch_shift(input_audio, fs, shift)
            if "RP_toggle" in result:
                # 入力の範囲は1~100なので、それを1~2になるように調整
                threshold = (int(result["RP_threshold"]) + 98) / 99
                # 処理速度を早めるため、窓長は1024で固定
                win_len = 1024
                output_audio, fs = process.robopitch(input_audio, fs, win_len, threshold)
                sf.write(filepath, output_audio, fs, subtype='FLOAT')
            else:
                # 加工なしの音声をstaticに保存
                sf.write(filepath, input_audio, fs)
            return render_template("processor/index.html", filename=filename, result=result, imagefile=session["target_images"][number], number=number)
        else:
            answer = Answer(
                uuid=session["uuid"],
                image_path=session["target_images"][number],
                audio_path=session["original_audio"][number],
                processed="RP_toggle" in result,
                threshold=(int(result["RP_threshold"]) + 98) / 99 if "RP_toggle" in result else "",
                window_length=1024 if "RP_toggle" in result else "",
                pitch_shifted="pitch_toggle" in result,
                pitch_shift=int(result["pitch_shift"]) if "pitch_toggle" in result else "",
            )
            db.session.add(answer)
            db.session.commit()
            if number + 1 == session["total"]:
                return redirect(url_for("guide.end"))
            else:
                return redirect(url_for("processor.index", number=number+1))
    
@processor.route("/audio/<path:filename>")
def audio_file(filename):
    return send_from_directory(current_app.config["UPLOAD_FOLDER"], filename)

@processor.route("/image/<path:filename>")
def image_file(filename):
    return send_from_directory(current_app.config["UPLOAD_FOLDER"], filename)

apps/processor/templates/processor/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>WebApp</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><!--表示サイズ,初期拡大率,適切な設定-->
        <link rel="stylesheet" href="{{ url_for('processor.static', filename='style.css') }}">
    </head>
    <body>
        {% block content %}{% endblock %}
    </body>
</html>

apps/processor/templates/processor/index.html
{% extends "processor/base.html" %}
{% block content %}
<div class="container">
    <p>
        画像のイメージに合うように、音声を加工してください。
    </p>
    <form method="POST" class="form">
        <div class="question-number">
            問 {{ number + 1 }} / {{ session["total"] }}
        </div>
        <img src="{{ url_for('processor.image_file', filename=imagefile) }}" alt="ロボット画像" class="robot-image">
        <div class="btns">
            <!-- 送信時にrangeの値をhiddenにコピーする関数を走らせる -->
            <input type="submit" name="button" value="再生" onclick="rangeValueCopy()" id="playButton" class="btn btn-play">
            <time id="currentPosition">0:00</time> / <time id="endPosition">0:00</time>
            <button type="button" onclick="resetParameter()" class="btn btn-reset">リセット</button>
            <input type="submit" name="button" value="この音声で決定" class="btn btn-decision">
        </div>
        <div class="methods">
            <div class="method">
                {% if result['RP_toggle'] %}
                    <label class="toggle">
                        <input type="checkbox" id="RobopitchToggle" name="RP_toggle" onchange="RobopitchOnchange()" checked>
                    </label>
                {% else %}
                    <label class="toggle">
                        <input type="checkbox" id="RobopitchToggle" name="RP_toggle" onchange="RobopitchOnchange()">
                    </label>
                {% endif %}
                <b>音声を機械的に加工</b>
                <p>加工の強さ：<span id="currentThreshold"></span></p>
                {% if result['RP_toggle'] %}
                    <input type="range" class="range" id="RobopitchThreshold" name="RP_threshold" min="1" max="100" value="{{ result['RP_threshold'] }}" step="1">
                {% elif result['RP_threshold'] %}
                    <!-- toggleが選択されていないときはdisabledに -->
                    <input type="range" class="range" id="RobopitchThreshold" name="RP_threshold" min="1" max="100" value="{{ result['RP_threshold'] }}" step="1" disabled>
                {% else %}
                    <input type="range" class="range" id="RobopitchThreshold" name="RP_threshold" min="1" max="100" value="1" step="1" disabled>
                {% endif %}
                <!-- rangeがdisabledのとき、valueを送信することができたいため、hiddenにvalueをコピーして送信する -->
                <!-- 受信側で同様に処理できるようにnameは同じに -->
                <input type="hidden" class="hidden" name="RP_threshold" value="">
                <!-- <p>窓長：<span id="currentWindowLength"></span></p>
                {% if result['RP_toggle'] %}
                    <input type="range" class="range" id="RobopitchWindowLength" name="RP_win_length" min="512" max="1024" value="{{ result['RP_win_length'] }}" step="512">
                {% elif result['RP_win_length'] %}
                    <input type="range" class="range" id="RobopitchWindowLength" name="RP_win_length" min="512" max="1024" value="{{ result['RP_win_length'] }}" step="512" disabled>
                {% else %}
                    <input type="range" class="range" id="RobopitchWindowLength" name="RP_win_length" min="512" max="1024" value="512" step="512" disabled>
                {% endif %}
                <input type="hidden" class="hidden" name="RP_win_length" value=""> -->
            </div>
            <div class="method">
                {% if result['pitch_toggle'] %}
                    <label class="toggle">
                        <input type="checkbox" id="pitchToggle" name="pitch_toggle" onchange="pitchOnchange()" checked>
                    </label>
                {% else %}
                    <label class="toggle">
                        <input type="checkbox" id="pitchToggle" name="pitch_toggle" onchange="pitchOnchange()">
                    </label>
                {% endif %}
                <b>音声の高さを調整する</b>
                <p>高さの変化: <span id="currentShift"></span></p>
                {% if result['pitch_toggle'] %}
                    <input type="range" class="range" id="pitchShift" name="pitch_shift" min="-50" max="50" value="{{ result['pitch_shift'] }}" step="1">
                {% elif result['pitch_shift'] %}
                    <input type="range" class="range" id="pitchShift" name="pitch_shift" min="-50" max="50" value="{{ result['pitch_shift'] }}" step="1" disabled>
                {% else %}
                    <input type="range" class="range" id="pitchShift" name="pitch_shift" min="-50" max="50" value="0" step="1" disabled>
                {% endif %}
                <input type="hidden" class="hidden" name="pitch_shift" value="">
            </div>
        </div>
    </form>
</div>
{% if filename %}
<audio src="{{ url_for('processor.audio_file', filename=filename) }}" type="audio/wav"></audio>
{% endif %}
<script src="{{ url_for('processor.static', filename='script.js') }}"></script>
{% endblock %}